[Scheme]
Name=Horizon Candy Milk
ColorForeground=#06060C
ColorBackground=#FDF0ED
ColorCursor=#E84A72
ColorCursorForeground=#06060C
ColorCursorUseDefault=FALSE
ColorSelectionBackground=#AF542780
ColorSelection=#06060C
ColorSelectionUseDefault=FALSE
TabActivityColor=#E84A72
ColorPalette=#F9CBBE;#F43E5C;#1EB980B3;#FAB795;#26BBD9;#F075B5;#59E1E3;#06060C;#FADAD1;#EC6A88;#1EB980B3;#FBC3A7;#3FC4DE;#F075B5;#6BE4E6;#1A1C23
